site_name: github pages tryout
site_description: 'A mkdocs test'
site_author: 'Martin Demling'
docs_dir: docs/
repo_name: '0x6d64/ghpages-tryout'
repo_url: 'https://github.com/0x6d64/ghpages-tryout'

nav:
    - Home: index.md
theme:
  name: 'material'

markdown_extensions:
  - pymdownx.tilde
